---

- name: Converge
  hosts: all

  roles:
    - role: newrelic_agent_java
      sansible_newrelic_agent_java_install_dir: /opt/newrelic-test-agent-java
      sansible_newrelic_agent_java_settings:
        app_name: Test Application
        license_key: 123456789123456789123456789123456789
